server:
  port: 8181
  error:
    include-message=always:
spring:
  application:
    name: user-service
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5433/customer?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: playnetz
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
  main:
#    allow-bean-definition-overriding: true
    allow-circular-references: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#Key depends on jwt algorithm: If RSA => needs public, private; if HMAC => NEEDS ONLY single key....
app:
  jwt:
    secret: RandomSecretKey1234567890!RandomSecretKey1234567890!RandomSecretKey1234567890!RandomSecretKey1234567890!
    expiration-in-ms: 86400000

service:
  security-secure-key-username: randomSecureKeyUsername!
  security-secure-key-password: randomSecureKeyPassword
